language: go

go:
  - 1.5.1
  - 1.6.2
  - tip

sudo: false

script:
    - go get -v ./...
    - go test -v ./...

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always

